### PR TITLE
Replace Word (docx) with comparable markdown (md) file for adding artifact repo

### PR DESCRIPTION
**Pull request by d3r3kk**
- Add markdown file
- Remove Word (docx) file
- Add necessary images into the Documentation/images subfolder
- Redo the Word document as markdown

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@d3r3kk__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by ryanvog** [comment]
Please squash your commits

**Comment by mithunshanbhag** [comment]
LGTM.

**Comment by mithunshanbhag** [comment]
@d3r3kk, please do squash your commits for future PRs :-)

**Pull request merged**
