### PR TITLE
Added support for vhds in the genereated vhds folder

### PR DESCRIPTION
**Pull request by ericame**
The Get-AzureRmDtlVhd cmdlet currently only looks in the uploads container for vhds, but the lab also supports the generatedvhds container. Updated the cmdlet to match the lab's functionality.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ericame__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ericame). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by mithunshanbhag** [comment]
@ericame: is this functionality needed for image factory?

**Comment by ericame** [comment]
@mithunshanbhag yes - currently, I just call the same code directly that this cmdlet calls so as to not be blocked by this, but I'd prefer to use the cmdlet.

**Comment by mithunshanbhag** [comment]
LGTM. But please retarget your PR to **mithuns/NewCommunity** branch

**Comment by ericame** [comment]
Merging to different branch, closing review

**Pull request closed without merging**
