### PR TITLE
Fix Get AzureRM major version

### PR DESCRIPTION
**Pull request by remote-specialist**
Get-Module -Name "AzureRM" -ListAvailable | Sort-Object Version.Major -Descending | Select-Object -First 1

this code will return version 5 if version 5 and 6 are installed

### CODE REVIEW

**Comment by petehauge** [comment]
Thanks for looking into this!  I installed multiple versions of Azure RM including 5 + 6 and ran the original code, and it works as expected.  The new code also works for this case.

Unfortunately, if there is NO AzureRM module installed there's an error with the new code..

azurermversion


azurermversionerror

**Comment by remote-specialist** [comment]
For me, it does not work. In my case, I got the same results with and without -Descending flag
screen1

**Comment by petehauge** [comment]
How about we do something like this?  It's your code with ignoring the error so we don't end up with a failure if the user doesn't have AzureRM installed at all:

Get-InstalledModule -Name "AzureRM" -ErrorAction SilentlyContinue

**Comment by remote-specialist** [comment]
For me, such a solution is perfectly fine

**Pull request merged**
